npmPublishRegistry: "https://registry.npmjs.org/"

npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version-tools.cjs
    spec: packages/yarn-plugin-version-tools/bundles/@yarnpkg/plugin-version-tools.js

yarnPath: .yarn/releases/yarn-3.2.0.cjs
